export const ADD_PROJECT = 'ADD_PROJECT'

export const CREATE_UPDATE_PROJECT_FAIL = 'CREATE_UPDATE_PROJECT_FAIL'

export const FETCH_PROJECTS_START = 'FETCH_PROJECTS_START'
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS'
export const FETCH_PROJECTS_FAIL = 'FETCH_PROJECTS_FAIL'

export const FETCH_PROJECT_BY_PROJECT_ID_SUCCESS = 'FETCH_PROJECT_BY_PROJECT_ID_SUCCESS'
export const FETCH_PROJECT_BY_PROJECT_ID_FAIL = 'FETCH_PROJECT_BY_PROJECT_ID_FAIL'

export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS'
export const DELETE_PROJECT_FAIL = 'DELETE_PROJECT_FAIL'