export const CREATE_UPDATE_PROJECT_FAIL = 'CREATE_UPDATE_PROJECT_FAIL'

export const FETCH_PROJECTS_START = 'FETCH_PROJECTS_START'
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS'
export const FETCH_PROJECTS_FAIL = 'FETCH_PROJECTS_FAIL'

export const FETCH_PROJECT_BY_PROJECT_ID_SUCCESS = 'FETCH_PROJECT_BY_PROJECT_ID_SUCCESS'
export const FETCH_PROJECT_BY_PROJECT_ID_FAIL = 'FETCH_PROJECT_BY_PROJECT_ID_FAIL'

export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS'
export const DELETE_PROJECT_FAIL = 'DELETE_PROJECT_FAIL'

// project task type
export const CREATE_UPDATE_PROJECT_TASK_FAIL = 'CREATE_UPDATE_PROJECT_TASK_FAIL'

export const FETCH_PROJECT_TASKS_START = 'FETCH_PROJECT_TASKS_START'
export const FETCH_PROJECT_TASKS_SUCCESS = 'FETCH_PROJECT_TASKS_SUCCESS'
export const FETCH_PROJECT_TASKS_FAIL = 'FETCH_PROJECT_TASKS_FAIL'

export const FETCH_PROJECT_TASK_BY_ID_SUCCESS = 'FETCH_PROJECT_TASK_BY_ID_SUCCESS'
export const FETCH_PROJECT_TASK_BY_ID_FAIL = 'FETCH_PROJECT_TASK_BY_ID_FAIL'

export const DELETE_PROJECT_TASK_SUCCESS = 'DELETE_PROJECT_TASK_SUCCESS'
export const DELETE_PROJECT_TASK_FAIL = 'DELETE_PROJECT_TASK_FAIL'

// user
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'

export const LOGIN_START = 'LOGIN_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const CLEAR_LOGIN_ERROR = 'CLEAR_LOGIN_ERROR'

export const LOGOUT = 'LOGOUT'